version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: toto_dodo
      POSTGRES_DB: todo_toto
    ports:
      - "5433:5432"
  todo_app:
    container_name: todo_app
    build:
      context: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: False
      SECRET_KEY: 'django-insecure-dz=-f3x%^_z6c7$rxo!th0_xe7ljwf7o)s=#pe*1wwud&4pi2b'
      DB_NAME: todo_toto
      DB_USER: myuser
      DB_PASSWORD: toto_dodo
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - todo_app
volumes:
  static_volume: